[service.api]
listen_address = ":8045"

[service.api.tls]
enable = false
cert_file = ""
cert_key = ""

[logger]
enable_console = true
console_json = false
console_level = "INFO"
enable_file = true
file_json = true
file_level = "DEBUG"
file_location = "rtcd.log"
enable_color = true

